version: '3.1'
services:
  ansible-node1:
    image: local/ansible-node
    container_name: ansible-node1
    hostname: ansible-node1
    networks:
      ansible-default:
        ipv4_address: 10.0.0.2
    ports: 
      - "8881:80"

  ansible-node2:
    image: local/ansible-node
    container_name: ansible-node2
    hostname: ansible-node2
    networks:
      ansible-default:
        ipv4_address: 10.0.0.3
    ports: 
      - "8882:80"

  ansible-host:
    image: local/ansible-host
    container_name: ansible-host
    hostname: ansible-host
    tty: true
    networks:
      ansible-default:
        ipv4_address: 10.0.0.1

networks:
  ansible-default:
    ipam:
      driver: default
      config:
         - subnet: "10.10.10.0/24"
