FROM ubuntu:latest

RUN apt-get update && \
    apt-get install -y openssh-server&& \
    apt-get clean all

# python and relevant tools
RUN apt-get update && apt-get install -y \
    python3 \
    python3-dev \
    libssl-dev \
    python3-pip

RUN pip3 install --upgrade pip setuptools

# Replace with your own timezone after zoneinfo/. Example: Europe/Athens
RUN ln -sf /usr/share/zoneinfo/Europe/Athens /etc/localtime

RUN mkdir /var/run/sshd
RUN sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_config
RUN mkdir /root/.ssh
COPY id_rsa.pub /root/.ssh/authorized_keys

RUN chmod 400 /root/.ssh/authorized_keys

EXPOSE 1-65535

CMD mkdir -p /run/sshd && /usr/sbin/sshd -D
