FROM ubuntu:latest 
RUN apt-get update && \
apt-get install -y openssh-server net-tools curl wget && \
apt-get clean all

# python and relevant tools 
RUN apt-get update && apt-get install -y \ 
python3 \ 
python3-dev \ 
libxml2-dev \ 
libxslt-dev \ 
libssl-dev \ 
zlib1g-dev \ 
libyaml-dev \ 
libffi-dev \ 
python3-pip # Latest versions of python tools via pip 

RUN pip3 install --upgrade pip \ 
virtualenv \ 
requests

# Replcale with your own timezone after zoneinfo/ . Example: Europe/Athens
RUN ln -sf /usr/share/zoneinfo/Europe/Athens /etc/localtime

RUN mkdir /var/run/sshdRUN 
RUN sed -ri 's/^PermitRootLogin\s+.*/PermitRootLogin yes/' /etc/ssh/sshd_config

RUN sed -ri 's/UsePAM yes/#UsePAM yes/g' /etc/ssh/sshd_configRUN 
RUN mkdir /root/.ssh
COPY id_rsa.pub /root/.ssh/authorized_keys

RUN chmod 400 /root/.ssh/authorized_keys

EXPOSE 1-65535
CMD ["/usr/sbin/sshd", "-D"]
