version: '3'
services:
  ansible-node1:
    image: steveiliop56/ansible-node
    name: ansible-node1
    hostname: ansible-node1.local
    networks:
      ansible-default:
        ipv4_address: 10.0.0.2
    ports: 
      - "8081:80"

  ansible-node2:
    image: steveiliop56/ansible-node
    name: ansible-node2
    hostname: ansible-node2.local
    networks:
      ansible-default:
        ipv4_address: 10.0.0.3
    ports: 
      - "8082:80"

  ansible-host:
    image: steveiliop56/ansible-host
    name: ansible-host
    hostname: ansible-host
    tty: true
    networks:
      ansible-default:
        ipv4_address: 10.0.0.1

networks:
  ansible-default:
    ipam:
      driver: default
      config:
         - subnet: "10.10.10.0/24"
